-- 1. Create the Branches Table
create table branches (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  location text,
  status text default 'ONLINE' -- ONLINE, OFFLINE, WARNING
);

-- 2. Create the Sensor Logs Table (Big Data)
create table sensor_logs (
  id bigint generated by default as identity primary key,
  branch_id uuid references branches(id),
  sensor_type text not null, -- 'diesel', 'temp_cold', 'sales'
  value numeric not null,
  recorded_at timestamptz default now()
);

-- 3. Enable Realtime for these tables
alter publication supabase_realtime add table branches;
alter publication supabase_realtime add table sensor_logs;

-- 4. Seed some initial data (Your Branches)
insert into branches (name, location) values 
('Lekki Phase 1', 'Lagos'),
('Ikeja City Mall', 'Lagos'),
('Onitsha Mall', 'Anambra');

-- 5. Create the Webhook/Edge Function Trigger
-- Note: In a real Supabase instance, you would use the UI to set up a Database Webhook
-- strictly speaking, or use the pg_net extension if available.
-- For this "Project Setup", we will define the internal function stub that *would* call the edge function.
-- However, for the most robust "Demo", we often rely on the Client (Vue) or an external script to push alerts
-- or use Supabase's built-in "Database Webhooks" feature which is configured in the Dashboard, not just SQL.
-- BUT, we can add a comment here to serve as documentation for the "Ghost Hardware".

-- Ideally:
-- create trigger on_critical_sensor_log
-- after insert on sensor_logs
-- for each row execute function supabase_functions.http_request(...);

